---
# General
PROJECT_NAME: "assistance"
PROJECT_ROOT: "/home/x02/dev/server_platform_assistance"
PROJECT_REPO: "git@github.com:Telecooperation/server_platform_assistance.git"

# ActiveMQ
ACTIVEMQ_VERSION: "5.14.0"
ACTIVEMQ_USER: "activemq"
ACTIVEMQ_INSTALLATION_DIR: "/usr/share/activemq"
ACTIVEMQ_PORT_61616_TCP_ADDR: "127.0.0.1"
ACTIVEMQ_PORT_61616_TCP_PORT: "61616"

# Postgres
POSTGRES_SYSTEM_USER: "assistance-postgres"
POSTGRES_DB_NAME: "assistance-postgres"
POSTGRES_DB_USER: "assistance-postgres"
POSTGRES_DB_PASS: "assistancepass"
DB_PORT_5432_TCP_ADDR: "127.0.0.1"
DB_PORT_5432_TCP_PORT: "5432"

# Cassandra
CASSANDRA_IP: "127.0.0.1" # TODO: replace in config
CASSANDRA_PORT_9042_TCP_ADDR: "127.0.0.1"
CASSANDRA_PORT_9042_TCP_PORT: "9042"